[fix] targetを_blankに変更
Mori-Atsushi/SyncPodWeb pull request #13
Opened 2019-03-15 13:33 UTC by meokz

close #12

2019-03-15 13:43 UTC, mori-atsushi requested changes
お手数ですが `room.html` の方も見て頂けますでしょうか。

2019-03-16 04:02 UTC, meokz commented
承知いたしました

2019-03-16 04:06 UTC, meokz commented
@Mori-Atsushi 修正しました。確認のほどよろしくお願いいたします。

2019-03-16 04:11 UTC, mori-atsushi approved these changes
:igyo:

2019-03-16 04:11 UTC, merged